
---
title: "Picking Up the Pieces of Macro Theory"
subtitle: "The 2007 Crisis and Where to Go From Here?"
author: "Matthew Aaron Looney"
date: "April 28, 2018"

output:
  pdf_document:
    fig_caption: yes
    number_sections: no
    toc: no
    toc_depth: 4
  html_document:
    toc: yes
    toc_depth: '4'
    
abstract: "
It has been estimated that the global financial (GFC) crisis has cost the world somewhere between $5-30 trillion USD. By any comparison this is a staggering loss and represents the most serious failure of economic systems since the 1920's. There were many reasons for the 2007 crisis, and analysis is ongoing, but what seems to be emerging as the leading cause of the crisis was the lack of macroeconomic models to account for major sectors of the economy, mainly the housing sector and financial asset pricing. Just as important, but perhaps more theoretically challenging to address, were the lack of heterogeneity of economic agents, the lack of (or inappropriate) micro-foundation underpinnings, and the failure to relax the requirement of rational expectations. The singular focus of macroeconomists and central bankers, pre-crisis, was on the Dynamic Stochastic General Equilibrium model (DSGE). None of the DSGE models were capable of alerting economists to the impending crisis.  
In this paper I examine the modeling paradigm pre-crisis and review the literature that has dawned as a result of the GFC. Much of this literature has been written by well-regarded macroeconomists and is highly critical of the field. The criticism cuts deep and results in a range of suggestions that include; adding elements to the DSGE framework to account for missing variables, to starting over with a completely new way to model complicated and emergent systems, ie. Agent Based Modeling.  
"
    
header-includes:
- \usepackage{graphicx}
- \usepackage{rotating}
- \usepackage{longtable}
- \usepackage{amssymb,amsmath}
- \usepackage{dcolumn}
- \usepackage{setspace}
- \usepackage{mathrsfs}
- \usepackage{eso-pic,graphicx,transparent}

bibliography: LitReviewPaperBib.bib
csl: computational-economics.csl
link-citations: true
fontsize: 12pt
geometry: margin = 1.25in

---

\AddToShipoutPictureFG{
  \AtPageCenter{% or \AtTextCenter
    \makebox[0pt]{\rotatebox[origin=c]{45}{%
      \scalebox{5}{\texttransparent{0.05}{DRAFT}}%
    }}
  }
}

\doublespacing
\newpage

-----
## Introduction
  
  
\qquad Our ability to understand how and why the global financial crisis (GFC) occurred is predicated on our ability to understand past financial crisis, which in turn shaped the current environment that facilitated the most recent financial crisis. In some regard, financial crisis are cyclical. What I mean by this is as follows, a financial crisis starts, regulators respond to the crisis by implementing policies to avoid future crisis. Economists develop new models to deal with the failings of the old models in the hopes of better predicting future crisis. Complacency sets in and regulations are picked apart which, more often than not, amplify the negative effects of the unintended consequences of well intended regulators. After sufficient time, a new crisis forms and the cycle starts anew. If we are to understand the current crisis we need some context from past crisis to frame how we arrived in the current situation.
  
  
## Past Crisis - A very short history

\qquad Financial crisis are not a recent phenomena. Since the 1920's the United States has endured a number of them, including a large depression, a large recession, and everything in between. With each occurrence regulators and economists spring to action with the hope of understanding, modeling and developing regulation to address future failings in the economic system. Less than one hundred years ago the U.S. was in the throws of the Great Depression. By the time the depression was over John Maynard Keynes had reformulated Alfred Marshall's partial equilibrium model with the inclusion of nominal rigidities. This reformulation required Keynes to invent several new concepts including liquidity preference, the consumption function and the multiplier. These components were necessary if Keynes was going to explain the Great Depression with his new ideas. However, Keynes' conceptual reformulation would only go so far. A methodological reformulations was also needed if the ideas Keynes proposed were going to take hold in any meaningful way. John Hicks provided the necessary methods in his IS-LM model and the foundations for general equilibrium analysis were set forth.  
  
  
\qquad After the Great Recession the economy was slow to recovery but was helped along by the start of WWII. After the war was over the economy was humming and economists were hard at work continuing to refine and develop additions to the IS-LM framework. Two influential papers on stabilization policy were written by Phillips (1954, 1957). These papers gave policy makers what they wanted; a link between the rate of unemployment and the rate of inflation. If policy makers wanted lower levels of unemployment they could simply turn the lever and magically lower unemployment, albeit at a higher rate of inflation. The seeming success of the Phillips curve led to an explosion of empirical macroeconomic models including models developed by Frisch, Goldberger, Haavelmo, Klein, and Tinbergen. This work culminated in the first economy-wide macroeconomic model which was used to lend credibility to the macroeconomic policy making advocated for by the Phillips model.^[For a more detailed discussion of this model (the Federal Reserve System's MPS model) see Goodfriend and King [-@Goodfriend:1997ws] ]  
  
  
\qquad However, the success of the early macro-models was short lived. During the 1970's and 1980's a deep recession took hold. The recession was accompanied by high levels of unemployment and high levels of inflation. According to the prevailing macroeconomic models in current use this should not have been possible. Macroeconomists had a very public problem on their hands. As a result of this disparity between what the phillips curve predicted should be happening when unemployment was high and what was actually happening; the macroeconomists needed to refine their models and fast. This gave rise to what was to become known as the New Keynesian economics. Rather than start over with a completely new model the New Keynesians got to work adding complexity to their models to explain why we might see high inflation and high unemployment. Their focus, initially, was on the idea that wages and prices must be sticky. This stickiness of wages and prices could explain, why in the short run, it was possible to have both high unemployment and high inflation. In addition to the stickiness concept, New keynesians poured a lot of effort into development of the Dynamic Stochastic General Equilibrium (DSGE) model, a model that was destined to take center stage in the macroeconomic revolution. The DSGE model incorporates elements of endogenous capital stock and investment and is a microfounded representative agent model. Since the model contains both supply and demand analysis and has elements of the labor market, money market, and equity market the model is a true general equilibrium model. There is no universally agreed upon formulation as to the exact mathematical structure of the DSGE model however, most of the DSGE models contain the same basic ingredients. A short exposition of the DSGE model is given in Appendix A.  
  
  
## The Global Financial Crisis and the DSGE Model
\qquad The trend in macroeconomics since the 1980's has been focused almost exclusively on the DSGE model. The model has become more rich and complicated over the past several decades. As with any modeling paradigm, economic models are intended to provide simplified insight into very complicated situations and the DSGE model is no different in this regard. The problem with the DSGE model was that policy makers were starting to view this class of model in the same way they had viewed the Phillips curve type models pre Great Recession. Adding to the problem, economists were omitting key segments of the economy in an effort to keep the model tractable. However, this tractability came at a steep cost. In an effort to keep the DSGE models manageable, economists were forced to make unreasonable modeling assumptions. These assumptions alone were not a serious problem as long as the modeler and those seeking to use the model for policy prescriptions understand the models limitations. Either the assumptions associated with the DSGE model were not well understood or were simply ignored, the end results was the same. A global economic recession took hold in the late 2000's. Although the recession was global in scale it is widely acknowledged that the recession originated in the Unites States and was centered around the subprime mortgage crisis.  
  
  
\qquad As a direct result of the GFC the field of macroeconomics found itself in the hot seat once again. Similar to the past crisis, economists rolled up their sleeves and started the process of pulling apart the crisis to understand where they had failed. However, this time economists are taking a more introspective approach when considering where exactly the models went wrong. This is partly brought on by the size and scope of the financial loss and party as a result of public outcry and congressional investigation. Through this soul searching many well regarded economists in the field of macroeconomics have weighed in on where they feel the models have failed, how to make the DSGE models more realistic and robust and/or alternative modeling methods to employ that may better represent the global economy. Although there is some disagreement as to the exact approach, many economists agree of a set of approaches that should be taken to ensure a crisis on the scale of the GFC does not occur again, or at the very least we should be able to have some advanced warning that an impending crisis is looming.^[While many authors argue that the GFC was plainly obvious and the warning signs were simply ignored this does not explain the fact that none of the DSGE models in use were able to detect a looming crisis. While I do acknowledge that bad policy and corporate greed played a key role, the focus of this paper is to explore modeling prescriptions outside of policy, in particular I am interested in how the DSGE model failed and what the recommendations are moving forward.]  
  
  
## The Current Literature
### Four Primamry Recomendations to improve the DSGE Model

\qquad Through my analysis of key papers that have examined the failings of the DSGE model since the 2007 GFC, four main themes seem to be consistent across many of them. These themes as summarized as follows^[A more extensive discussion of the general themes can be found in Vines and Wills.]:

  * rather than assume costless financial intermediation models need to incorporate financial frictions more realistically.

  * relax or eliminate the concept of rational expectations.
  
  * eliminate the assumption of the representative agent model in favor of heterogeneous agents.
  
  * ground the models in more appropriate micro-foundations.
  
  
\qquad The loudest criticism of the DSGE model has been the omission of financial frictions. This is an obvious first target considering the GFC started in the financial sector. This criticism is articulated in a paper by Hendry and Muellbauer [-@Hendry:2018jd]. While the authors criticism is focused on several different flavors of the DSGE model (most recently the DSGE COMPASS model) the take away from their paper is that all DSGE models failed to incorporate financial frictions. As a way to incorporate frictions into the DSGE model, Blanchard [-@Blanchard:2018ki] suggests adding liquidity constraints. Others suggests adding elements to capture debt financed investments and a mechanism to represent the financial accelerator (Carlin and Soskice 2014, 2018). Much of the literature has focused on incorporating some mechanism to capture detailed levels of financial friction. How exactly this is accomplished and to what degree are currently being debated in the literature. 

\qquad The rational expectations model has been a mainstay assumption in the macroeconomics literature since its introduction by John Muth in the 1960's. The rational expectations idea has become more of a way of thinking in the field of economics than a modeling assumption. However, the idea of the rational agent is very much an assumption and in many situations appears to be untrue. The validity of this assumption has been called into question and many macroeconomists have suggested relaxing the rational agent assumption in future modeling efforts. The complaints about rational agents are primarily two fold. First, several authors have argued that the rational agent is too forward looking.^[The loudest argument in favor of relaxing the rational expectations assumption can be found in Stiglitz (2018). However, the theme of loosening the rational expectations assumption can also be found in Blanchard, Ghironi, and Haldane and Turrell.] In other words, agents forward looking time horizons are too far into the future. The argument is centered around the idea that if the time horizons are too far out, this will lead to unrealistic consumption and price setting behavior.^[We can think of unrealistic consumption behavior as being related to the Euler equation and we can think of unrealistic price setting behaviors as being related to Calvo contracting.] Second, @blanchard2017distortions, in a similar argument against complete rational expectations suggests employing an upper bound on time horizons to more realistically deal with incomplete information and myopia in the decision making process. While relaxing the rational expectations assumption is expected to go a long way in developing a more accurate model of the macroeconomic environment, several authors have suggested that without also relaxing the representative agent assumption there is little hope for building a more realistic DSGE model.

\qquad Why use the assumption of a representative agent? The reasons for assuming a representative agent are two fold. First, many macroeconomists belief that any model developed to explain the global economy should allow for the distillation of core equations to a simple and universal formulation. The idea that “beauty is truth” is still prevalent in many scientific fields and economic social science is no exception.  A second, (and perhaps larger of the two) reason for assuming a representative agent model is for the pure tractability of the computation of the models. While it is not unreasonable to construct a baseline model with strong assumptions, these assumptions should be relaxed to build the model toward a more realistic representation of the world. Failing to relax strong assumptions in the DSGE model was driven mostly by the computational burden associated with, in this case, a heterogeneous agent model.^[However, many of the baseline assumptions in the DSGE model are driven by the manageability of the calculations. Right or wrong, these strong assumptions were so unrealistic that almost all inference based of these models was flawed at best.] With the advancements in computer hardware and computational algorithms, the concerns with model tractability are largely irrelevant. However, the DSGE models do explode in complexity when heterogeneous firms and households are incorporated. The true questions then becomes, how much realism is required to understand the salient features of the macro economy. Clearly, a representative agent model falls short in its ability to provide insights about the global economy. When we assume a representative agent, (households and firms) we are aggregating away many important features of the individual. For instance, take income as an example. As put forth in a paper by Stiglitz (2018), the distribution of income at the household and  firm level is important to understand for both demand and welfare analysis. If we take a representative agent and assume a point estimate for income the inference based on these point estimates will imply a set of policy prescriptions that may be far from the prescriptions that might be realized with a heterogeneous model. Even if we take individual country level income and the average firm in a given sector as being representative we are still smoothing away valuable information. It is not reasonable to assume all individuals living the the United Sates have a similar average income just as it is not reasonable to assume that all individuals living in China have a similar average income. The same logic applies to sectors of firms as argued by Ghironi (2018). Ravn and Sterk (2016) acknowledged that macroeconomic models have started moving in the direction of a pseudo-heterogeneous agent with the inclusion of several representations of households and firms. But they argue that the inclusion of several sectors of representative firms does little to get around the deep aggregation problem of smoothing out the important characteristics of firms and households. 

\qquad The three suggestions given above: incorporation of financial frictions, relaxing rational expectations, and allowing for heterogeneous agents are all important concepts that will move the DSGE model closer to a more realistic representation of the global economy. But perhaps the largest challenge comes when trying to incorporate aspects of micro-economic foundations. While microfounded macroeconomics is not a new concept, many authors have argued that either the micro concepts currently used in macroeconomics do not go far enough or the micro concepts that are currently used in macro models are not appropriate. Most authors agree that better micofoundations need to be integrated into the DSGE models. However, it is unclear from the literature where exactly in the DSGE model to build these concepts up. In other words, should macro modelers focus on the core benchmark model (see appendix A) or should micro-foundations be applied to the periphery of the DSGE models. Blanchard (2018) and Krugman (2018) both argue that the most appropriate location for micro concepts to be integrated into the DSGE model is in the core benchmark model. Krugman argued that the GFC occurred due, in part, to the lack of micro-foundations in the supply side of the core benchmark model and thus the majority of the focus should be on building up the supply and demand side of the core model with better micro-foundations. Balnchard agrees with Krugman's assessment of the general location of where to focus the micofoundations but argues that any new micro-foundation components need to extend beyond the simple demand and supply side price and wage setting. Blanchard argues that to ignore the costs of collecting information is likely to end in peril and advocates for micro-foundations that incorporate imperfect information. 

## A new Modeling paradigm - Agent Based Modeling












\newpage
# Appendix A

### The New Keynesian Dynamic Stochastic General Equillibrium Benchmark Model (DSGE)

A simplified version of the New Keynesian DSGE Benchmark Model (hereafter NK-DSGE) is given by the following eight equations^[A more detailed exposition of the benchmark model can be found in Schmitt-Grohe´ and Uribe [-@schmitt2007optimal] ]:
\singlespace
\begin{equation}
\frac{1}{{{C_t}}} = \beta {R_t}{E_t}\left( {\frac{1}{{{C_{t - 1}}}}} \right)
\end{equation}

\begin{equation}
{w_t} = {\rm X}{C_t}L_t^\varphi
\end{equation}

\begin{equation}
{Y_t} = {Y_t}K_t^\alpha L_t^{1 - \alpha }
\end{equation}

\begin{equation}
{w_t} = (1 - \alpha )\frac{{{Y_t}}}{{{L_t}}}
\end{equation}

\begin{equation}
{R_t} = {E_t}\left[ {\frac{{\alpha \frac{{{Y_{t + 1}}}}{{{K_{t + 1}}}} + 1 - \delta  + ({Q_{t + 1}} - 1) + \frac{1}{{2\xi }}{{({Q_{t + 1}} - 1)}^2}}}{{{Q_t}}}} \right]
\end{equation}

\begin{equation}
{I_t} = {K_{t + 1}} - (1 - \delta ){K_t} + \frac{\xi }{2}\frac{{{{({K_{t + 1}} - {K_t})}^2}}}{{{K_t}}}
\end{equation}

\begin{equation}
{Q_t} = 1 - \xi  + \xi \frac{{{K_{t + 1}}}}{{{K_t}}}
\end{equation}

\begin{equation}
{Y_t} = {C_t} + {I_t}
\end{equation}

where, $C$, $I$, $Y$, $L$, $K$, $w$, $R$, and $Q$ are consumption, investment, output, labor supply, capital stock, real wage, real interest rate (gross), and Tobin's Q, respectively.  
  
  
\doublespacing  
  
For simplicity, the individual consumers utility maximization problem is not explicitly shown. For the same reason, the representative firms profit maximization problem is not detailed. Equations 1-8 assume the first order conditions have been satisfied and equilibrium conditions exist. Another simplifying assumption is a constant labor force and the level of technology remains unchanged. 

---
nocite: | 
  @Phillips:1954un, @Phillips:1957vd, @Carlin:2018ev, 
  @carlin2014macroeconomics, @stiglitz2018modern, @ghironi2018macro, 
  @diamond2002archaeology
...


\newpage
\singlespace

# Refernces
  
<!-- The tentative literature I plan to explore during the literature review follows:   -->

<!--   * Vines, D., & Wills, S. (2018). The rebuilding macroeconomic theory project: an analytical assessment. Oxford Review of Economic Policy, 34(1-2), 1–42. -->
<!--     * On the future of macroeconomic models by Olivier Blanchard -->
<!--     * Ending the microfoundations hegemony by Simon Wren-Lewis -->
<!--     * Where modern macroeconomics went wrong by Joseph E. Stiglitz -->
<!--     * On the future of macroeconomics: a New Monetarist perspective by Randall Wright -->
<!--     * Is something really wrong with macroeconomics? by Ricardo Reis -->
<!--     * Good enough for government work? Macroeconomics since the crisis by Paul Krugman -->
<!--     * Stagnant productivity and low unemployment: stuck in a Keynesian equilibrium by Wendy Carlin and David Soskice -->
<!--     * Macro needs micro by Fabio Ghironi -->
<!--     * An interdisciplinary model for macroeconomics by A. G. Haldane and A. E. Turrell -->
<!--     * The  nancial system and the natural real interest rate: towards a ‘new benchmark theory model’ by David Vines and Samuel Wills -->
<!--     * DSGE models: still useful in policy analysis? by Jesper Lindé -->
<!--     * The future of macroeconomics: macro theory and models at the Bank of England by David F. Hendry and John N. J. Muellbauer -->
<!--     * Modelling a complex world: improving macro-models by Warwick J. McKibbin and Andrew Stoeckel -->

<!--   * Pesaran, M. H., & Smith, R. P. (2011). Beyond the DSGE straitjacket. Manchester School, 79(2), 5–16. -->

<!--   * Romer, P. (2016). The Trouble with Macroeconomics. Working Paper. -->

<!--   * C, M. K. (2013). Building a better model. Retrieved from https://www.economist.com/blogs/freeexchange/2013/01/remaking-macro-0 -->

<!--   * Wall, F. (2014). Artificial economics and self organization agent-based approaches to economics and social systems. -->

<!--   * Tesfatsion, L. (2006). Agent-Based Computational Economics: A Constructive Approach to Economic Theory. Computing in Economics and Finance 2006. Society for Computational Economics. -->

<!--   * Borrill, P. L., & Tesfatsion, L. (2010). Agent-Based Modeling: The Right Mathematics for the Social Sciences? Staff General Research Papers Archive. Iowa State University, Department of Economics. -->

<!--   * Rand, W., & Rust, R. T. (2011). Agent-based modeling in marketing: Guidelines for rigor. International Journal of Research in Marketing, 28(3), 181–193. -->

<!--   * Diamond, J. M. (2002). Archaeology: Life with the artificial Anasazi. Nature, 419(6907), 567. -->